#!/bin/sh
if [ -z "$JAVA_HOME" ]
then
    export JAVA_HOME=`java -XshowSettings 2>&1 | perl -ne 'print "$1" if /java\.home\s*=\s*(.*)/'`
    export JAVA_HOME=`dirname "$JAVA_HOME"`
    echo "JAVA_HOME isn't defined, guessing \`$JAVA_HOME\`"
fi
carton install
